server:
  port: 8761

spring:
  profiles:
    include:
    active:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false